// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Giraffe.QueryReader")>]
[<assembly: AssemblyProductAttribute("Giraffe.QueryReader")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-06-03T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","f0c3e549b13c4b480fb398f58c063456901c24d0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Giraffe.QueryReader"
    let [<Literal>] AssemblyProduct = "Giraffe.QueryReader"
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-06-03T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
    let [<Literal>] AssemblyInformationalVersion = "2.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "f0c3e549b13c4b480fb398f58c063456901c24d0"
