// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Giraffe.QueryReader")>]
[<assembly: AssemblyProductAttribute("Giraffe.QueryReader")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-12-28T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","028ba38d3304d8b5fd4545b1df412e68b9d61a42")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Giraffe.QueryReader"
    let [<Literal>] AssemblyProduct = "Giraffe.QueryReader"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-12-28T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyInformationalVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "028ba38d3304d8b5fd4545b1df412e68b9d61a42"
